#!/bin/bash
#
# your job's name
#$ -N job_name
#
# shell for execution
#$ -S /bin/bash
#
# SGE queue
#$ -q parallel.q@@clustername
#
# pe request
#$ -pe pe_slots core_number
#
# work from current working directory
#$ -cwd
#
# set output file
#$ -o ./output_name
#
# set error file
#$ -e ./error_name
#

mpd &
mpicc c_file_name -O3 -lm -o out_file_name
time mpiexec -n core_number ./out_file_name

exit 0
